import { IncomeRow, ExpenseRow, Employee } from './types';

export const EXPENSE_TYPES = [
  'Rent (70sqm)',
  'Water Bill',
  'Wifi',
  'Mobile Bill',
  'Electric Bill',
  'Dental Supplies',
  'Assistant Salary',
  'Food',
  'Misc',
  'Marketing/Ads',
  'Equipment',
  'Lab Fee',
  'Tax',
  'Other'
];

export const INITIAL_EMPLOYEES: Employee[] = [
  { code: 'ER', name: 'Dr. Eugine Francis Romero', role: 'Dentist', baseSalary: 0, commissionRate: 0.10, tin: '293-182-938-000' },
  { code: 'GA', name: 'Dr. Giselle Abrogena', role: 'Dentist', baseSalary: 0, commissionRate: 0.10, tin: '401-293-182-000' },
  { code: 'KU', name: 'Dr. Karla Antonette Urbi', role: 'Dentist', baseSalary: 0, commissionRate: 0.10, tin: '123-456-789-000' },
  { code: 'Ryan', name: 'Ryan Bolonia', role: 'Assistant', baseSalary: 8000, commissionRate: 0, tin: '382-192-381-000' },
  { code: 'Mary', name: 'Marylo Millares', role: 'Assistant', baseSalary: 8000, commissionRate: 0, tin: '291-381-229-000' },
  { code: 'Arkin', name: 'Rheinn Arkin Imperial', role: 'Assistant', baseSalary: 8000, commissionRate: 0, tin: '311-203-918-000' }
];

export const INITIAL_INCOME: IncomeRow[] = [
  {
    date: '2026-06-01',
    duty: 'KU',
    patient: 'Reyes, Maria',
    procedure: 'Resto',
    labFee: 0,
    discount: 0,
    amountPaid: 3500,
    percentCommission: 10,
    pct: 0.1,
    paymentTerminal: 'Cash',
    ccMerchantFee: 0,
    hmo: 0,
    totalGross: 3500,
    salaryRestricted: 'DATA FOR ADMIN ONLY',
    netTotal: 3150
  },
  {
    date: '2026-06-01',
    duty: 'KU',
    patient: 'Santos, Pedro',
    procedure: 'Exo',
    labFee: 0,
    discount: 0,
    amountPaid: 1500,
    percentCommission: 10,
    pct: 0.1,
    paymentTerminal: 'Cash',
    ccMerchantFee: 0,
    hmo: 0,
    totalGross: 1500,
    salaryRestricted: 'DATA FOR ADMIN ONLY',
    netTotal: 1350
  },
  {
    date: '2026-06-02',
    duty: 'GA',
    patient: 'Lim, Anna',
    procedure: 'Op',
    labFee: 0,
    discount: 0,
    amountPaid: 800,
    percentCommission: 10,
    pct: 0.1,
    paymentTerminal: 'Cash',
    ccMerchantFee: 0,
    hmo: 0,
    totalGross: 800,
    salaryRestricted: 'DATA FOR ADMIN ONLY',
    netTotal: 720
  },
  {
    date: '2026-06-02',
    duty: 'ER',
    patient: 'Garcia, Jose',
    procedure: 'RCT',
    labFee: 0,
    discount: 0,
    amountPaid: 12000,
    percentCommission: 10,
    pct: 0.1,
    paymentTerminal: 'Credit Card',
    ccMerchantFee: 420,
    hmo: 0,
    totalGross: 12000,
    salaryRestricted: 'DATA FOR ADMIN ONLY',
    netTotal: 10380
  },
  {
    date: '2026-06-03',
    duty: 'KU',
    patient: 'Torres, Liza',
    procedure: 'LC',
    labFee: 0,
    discount: 0,
    amountPaid: 2200,
    percentCommission: 10,
    pct: 0.1,
    paymentTerminal: 'BPI',
    ccMerchantFee: 0,
    hmo: 0,
    totalGross: 2200,
    salaryRestricted: 'DATA FOR ADMIN ONLY',
    netTotal: 1980
  },
  {
    date: '2026-06-04',
    duty: 'GA',
    patient: 'Cruz, Ben',
    procedure: 'Denture',
    labFee: 0,
    discount: 0,
    amountPaid: 8500,
    percentCommission: 10,
    pct: 0.1,
    paymentTerminal: 'Cash',
    ccMerchantFee: 0,
    hmo: 0,
    totalGross: 8500,
    salaryRestricted: 'DATA FOR ADMIN ONLY',
    netTotal: 7650
  },
  {
    date: '2026-06-05',
    duty: 'ER',
    patient: 'Dela Cruz, Mila',
    procedure: 'Odontec',
    labFee: 0,
    discount: 0,
    amountPaid: 15000,
    percentCommission: 10,
    pct: 0.1,
    paymentTerminal: 'Cash',
    ccMerchantFee: 0,
    hmo: 0,
    totalGross: 15000,
    salaryRestricted: 'DATA FOR ADMIN ONLY',
    netTotal: 13500
  },
  {
    date: '2026-06-06',
    duty: 'KU',
    patient: 'Bautista, Nena',
    procedure: 'Adjust',
    labFee: 0,
    discount: 0,
    amountPaid: 1500,
    percentCommission: 10,
    pct: 0.1,
    paymentTerminal: 'Gcash',
    ccMerchantFee: 0,
    hmo: 0,
    totalGross: 1500,
    salaryRestricted: 'DATA FOR ADMIN ONLY',
    netTotal: 1350
  },
  {
    date: '2026-06-07',
    duty: 'GA',
    patient: 'Ramos, Tony',
    procedure: 'Xray',
    labFee: 0,
    discount: 0,
    amountPaid: 350,
    percentCommission: 10,
    pct: 0.1,
    paymentTerminal: 'Cash',
    ccMerchantFee: 0,
    hmo: 0,
    totalGross: 350,
    salaryRestricted: 'DATA FOR ADMIN ONLY',
    netTotal: 315
  },
  {
    date: '2026-06-08',
    duty: 'ER',
    patient: 'Fernandez, Amy',
    procedure: 'PPM',
    labFee: 0,
    discount: 0,
    amountPaid: 10000,
    percentCommission: 10,
    pct: 0.1,
    paymentTerminal: 'Credit Card',
    ccMerchantFee: 350,
    hmo: 0,
    totalGross: 10000,
    salaryRestricted: 'DATA FOR ADMIN ONLY',
    netTotal: 8650
  }
];

export const INITIAL_EXPENSES: ExpenseRow[] = [
  { id: 1, date: '2026-06-01', type: 'Rent (70sqm)', description: 'Monthly clinic rent', amount: 18000 },
  { id: 2, date: '2026-06-01', type: 'Water Bill', description: 'Maynilad', amount: 610 },
  { id: 3, date: '2026-06-01', type: 'Wifi', description: 'PLDT Fiber', amount: 1399 },
  { id: 4, date: '2026-06-01', type: 'Mobile Bill', description: 'Globe postpaid', amount: 606 },
  { id: 5, date: '2026-06-01', type: 'Dental Supplies', description: 'Gloves, composites', amount: 7444 },
  { id: 6, date: '2026-06-01', type: 'Assistant Salary', description: 'Ryan + Mary + Arkin + Mika', amount: 18300 },
  { id: 7, date: '2026-06-01', type: 'Food', description: 'Staff meals', amount: 7296 },
  { id: 8, date: '2026-06-01', type: 'Misc', description: 'Various', amount: 16817.75 },
  { id: 9, date: '2026-06-01', type: 'Marketing/Ads', description: 'Facebook ads', amount: 7500 },
  { id: 10, date: '2026-06-01', type: 'Equipment', description: 'Chair installment', amount: 11250 },
  { id: 11, date: '2026-06-01', type: 'Other', description: 'Frontier', amount: 5890 },
  { id: 12, date: '2026-06-01', type: 'Other', description: 'L218', amount: 19000 }
];
